import Head from "next/head";
import Link from "next/link";
import styles from '../styles/Home.module.css'

const Navbar = () => {

    return (
        <div className={styles.container}>
        <Head>
          <title>Learn Next JS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
            <ul>
                <li>
                    <Link href='/' prefetch={false}><a>Home</a></Link>
                </li>
                <li>
                    <Link href='/about' prefetch={false}><a>About</a></Link>
                </li>
                <li>
                    <Link href='/contacts' prefetch={false}><a>Contacts</a></Link>
                </li>
                <li>
                    <Link 
                        href={{
                            pathname: '/posts/[date]/[slug]',
                            query: {
                                date: '2023-01-01',
                                slug: 'happy-new-year',
                                foo: 'bar'
                            }
                        }}  
                    >
                        <a>Read This Post</a>
                    </Link>
                </li>
            </ul>

        </div>
      </div>
        
    )
}

export default Navbar;