import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const HomePage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Learning Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          This is homepage
        </h1>


        <div className={styles.grid}>
          <div style={{ width: 500, height: 200, position: 'relative', marginTop: '10px' }}>
            <Image 
              src={'https://images.unsplash.com/photo-1605460375648-278bcbd579a6'}
              layout='fill'
              objectFit='cover'
              alt='A beautiful English Setter'
            />
          </div>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} Jeff

        </a>
      </footer>
    </div>
  )
}

export default HomePage;
